### ISSUE TITLE
First page data always fetched in Pagination with PrimeFaces

### ISSUE THREAD

**Issue by tedliang** [philwebb/springfaces#40]
When I play around with your traveladvisor example, I found out whenever click the page other than the first one, the service code (eg. hotelService.getReviews) is executed  twice. The first one fetches the first page data. Another one fetches data for the page you clicked. 

After dug into your source code, I added 'setRowIndex(first);' in line 115 of PrimeFacesPagedDataModel.java. It seems to fix the problem. Are you ignoring the parameter 'first' for the 'load' method on purpose?

**Comment by philwebb** [comment]
Nice spot.  I have updated the code to hopefully fix the issue, but in a slightly different way than the one that you suggest as I don't think the row index should get changed on load.  Instead the total number of rows is cached and stored in with the state information.  The loading now assumes that the size is not likely to change between calls and if it has a previous value it will use it.  I am still not 100% sure this is the best solution, so I will leave this issue open and give it some more thought.

**Comment by tedliang** [comment]
Yeah, it works much better. Caching the row count is the best solution. Thanks for your prompt fixing. Really appreciate your kindness of sharing this great integration project. ATB

**Comment by philwebb** [comment]
Committed a improved fix.  Closing this issue.
