### ISSUE TITLE
UIMessageSource is hard to use with certain PrimeFaces Components

### ISSUE THREAD

**Issue by philwebb** [philwebb/springfaces#48]
See comments here http://coderphil.wordpress.com/2011/11/15/integrating-spring-javaserver-faces-internationalization-and-localization/

java.lang.ClassCastException: org.springframework.springfaces.message.ui.MessageSourceMap$MessageCodeValue cannot be cast to java.lang.String
at org.primefaces.component.commandbutton.CommandButtonRenderer.encodeMarkup(CommandButtonRenderer.java:57)

Root cause is that the MessageSourceMap does not return Strings.

**Comment by philwebb** [comment]
> Did some research about your implementation on Message Bundle and I reached the following solution:
> 
> https://github.com/pccampos/springfaces/commit/5442e4eb0647d5afadd4f9e0cd755402b8cd635b
> 
> With this code the org.springframework.springfaces.message.ui.UIMessageSource will always try to return string, unless it still have some parameters to be filled. The problem with my implementation is when you use object as a parameter, I'm search for the backets in this string too, but as I understood the code you can't combine the parameters type.

**Comment by pccampos** [comment]
The regex on the code won't detect ObjectMessageSource parameters, as it is expecting a number between {}.

**Comment by philwebb** [comment]
@pccampos Thanks for the suggestion and the patch.  I have tweaked it a little to support object messages as well.  There is also an option to disable it from the UIMessageSource component (although it is enabled by default).  Can you reopen the issue if anything does not work for you.

Cheers

**Comment by pccampos** [comment]
Great work Phil, by returning the .toString() rather than Exception is a clever idea. I'm having some problems with unit tests now, don't know how to fix. You may also look at my code, I did another change to messages. It will try to resolve the variable without any prefix when the prefixed property is not available.

**Comment by philwebb** [comment]
> I'm having some problems with unit tests now, don't know how to fix

What problems are you having?  The CI server seems OK (https://buildhive.cloudbees.com/job/philwebb/job/springfaces/), perhaps something broke with the merge?  Can you build my repo OK?

> You may also look at my code, I did another change to messages. It will try to resolve the variable without any prefix when the prefixed property is not available.

Where is this change?  I could not see it as part of https://github.com/pccampos/springfaces/commit/5442e4eb0647d5afadd4f9e0cd755402b8cd635b , am I missing something?

**Comment by pccampos** [comment]
This is the code: https://github.com/pccampos/springfaces/commit/09c46bde8de72f402b4cd1af3b5835bcf91dc7b7

The error persist, maybe is related to my locale, I will try to use en_US to build: https://gist.github.com/3287573

**Comment by pccampos** [comment]
Changed the locale and it worked.

**Comment by philwebb** [comment]
I have pushed a fix for the test failures, let me know if it still fails.  You might also want to try the integration tests (you need firefox installed)

```
mvn clean install -Pintegrationtest  
```

I have opened a new issue for resolving without a prefix (https://github.com/philwebb/springfaces/issues/49)
