### ISSUE TITLE
UISelectItemsConverter cannot be saved on the FacesContext

### ISSUE THREAD

**Issue by pccampos** [philwebb/springfaces#53]
When need to restore an UISelectOne or an UISelectMany that uses org.springframework.springfaces.selectitems.ui.UISelectItems from FacesContext (via StateHolder) a java.lang.InstantiationException is thrown. The reason for this is that UISelectItemsConverter is declared as an inner class.

I've studied two solution for this:
- Make UISelectItemsConverter transient implementing StateHolder and set isTransient to return always true. The problem is that the UISelect will return with converter null and it will occurs validation error;
- Make UISelectItemsConverter serializable. In this case the converter must be refactored as a common Class, this is a major work, and I need some ideas on how to do that, as the UISelectItemsConverter must be updated when the UISelectItems values is changed.

I can post this on your blog if you want. I've pushed a code on my fork where I transformed UISelectItemsConverter on a nested class, but I cant restore it properly, I will try to implement the StateHolder on it.

**Comment by philwebb** [comment]
Hi Pedro,

Could you attach a stack trace and let me know what JSF implementation you are using. Even better if you have a sample project that reproduces the issue.

**Comment by pccampos** [comment]
Hi Phil,

I've created an new showcase at:

https://github.com/pccampos/springfaces/tree/master/springfaces-samples/springfaces-showcase

in order to reproduce the issue. You should merge only the content from springaces-showcase into your base, as my base is updated to avoid the InstantiationException.

In order to reproduce the issue you need to access 

http://localhost:8080/springfaces-showcase/spring/selectitems/selectonejpapartial 

If you hit submit it will execute without problems, if you hit update and then submit you will reach the InstantiationException.

If you don't have the time to work on this issue I can do this, I only need a guidance.

Cheers,
Pedro

**Comment by pccampos** [comment]
I pushed a solution to this issue on my branch. The solution tries to get UISelectItems on the component children during getAsString method from SelectItemsConverter. That way SelectItemsConverter don't need to be abstract and it can be stored in the FacesContext.

**Comment by philwebb** [comment]
Nice work! I have incorporated your fix into the latest code.
